---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
  namespace: soumya
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: springcont
        image: soumya06in/spring-docker:1
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: 250m
        ports:
        - containerPort: 8085
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: soumya
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: spring-app
